Shop-MVC2/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Shop_MVC2.Models
{
  public class Category
  {
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public int ShowOrder { get; set; }
  }
}

Shop-MVC2/Models/ErrorViewModel.cs
using System;

namespace Shop_MVC2.Models
{
  public class ErrorViewModel
  {
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

Shop-MVC2/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Shop_MVC2.Data;
using Shop_MVC2.Models;
using System.Collections;
using System.Collections.Generic;

namespace Shop_MVC2.Controllers
{
  public class CategoryController : Controller
  {
    private readonly ApplicationDBContext _db;

    public CategoryController(ApplicationDBContext db)
    {
      _db = db; 
    }

    public IActionResult Index()
    {
      IEnumerable<Category> categoryList = _db.Categories;
      return View(categoryList);
    }
  }
}

Shop-MVC2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shop_MVC2.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Shop_MVC2.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

Shop-MVC2/Views/Category/Index.cshtml
@model IEnumerable<Shop_MVC2.Models.Category>

  <div class="container" p-3>
    <div class="row pt-4">
      <div class="col-6">
            <h2 class="text-primary">Category List</h2>
      </div>
      <div class="col-6 text-right">
            <a class="btn btn-success" asp-controller="Categories" asp-action="Create">Create new Category</a>
        </div>      
    </div>
    @if(Model.Count()>1)
    {
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>
              Category Mame
            </th>
            <th>
              Show Order
            </th>
          </tr>
        </thead>
        <tbody>
          @foreach (var item in Model)
         {
             <tr>
               <td width="50%"> @item.Name</td>
               <td width="30%">@item.ShowOrder</td>
             </tr>
         }
        </tbody>

      </table>
    }
    else
    {
      <p>No categories found</p>
    }
  </div>

Shop-MVC2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Shop-MVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop_MVC2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shop_MVC2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Shop_MVC2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>